[package]
name = "screener"
version = "0.1.0"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7.7", features = ["gettext-system"] }
gtk = { version = "0.10.3", package = "gtk4", features = ["gnome_49"] }

[dependencies.adw]
package = "libadwaita"
version = "0.8.1"
features = ["v1_6"]
